import 'reflect-metadata';
import * as bcrypt from 'bcryptjs';
import { AppDataSource } from './data-source';
import { OtpUser } from '../modules/auth/entities/otp-user.entity';
import { User, UserRole } from '../modules/auth/entities/user.entity';
import { Driver } from '../modules/driver/entities/driver.entity';

const log = (msg: string): void => {
  // eslint-disable-next-line no-console
  console.log(msg);
};

async function seedAdminUser(): Promise<void> {
  const repo = AppDataSource.getRepository(User);
  const email = process.env.SEED_ADMIN_EMAIL ?? 'admin@sendo.local';
  const password = process.env.SEED_ADMIN_PASSWORD ?? 'ChangeMe!123';

  const existing = await repo.findOne({ where: { email } });
  if (existing) {
    log(`ℹ️  Admin user already exists: ${email}`);
    return;
  }
  await repo.save(
    repo.create({
      email,
      fullName: 'Sendo Admin',
      password: await bcrypt.hash(password, 12),
      role: UserRole.ADMIN,
    }),
  );
  log(`✅ Seeded admin user: ${email}`);
}

/**
 * Seed a driver tied to the developer's phone so OTP login flows have a real
 * `drivers` row to land on. We do NOT pre-seed an OTP — every login must go
 * through `POST /send-otp/sended` so the OTP is freshly generated by the
 * server. Without Twilio creds, OtpService logs the OTP to the backend
 * console; with Twilio, it's delivered via SMS.
 *
 * If a stale static OTP exists for this phone (from older seed versions),
 * it is purged here so it can't be re-used.
 */
async function seedDriver(): Promise<void> {
  const driverRepo = AppDataSource.getRepository(Driver);
  const otpRepo = AppDataSource.getRepository(OtpUser);

  const driverId = process.env.SEED_DRIVER_ID ?? 'DR-ADM-001';
  const rawPhone = process.env.SEED_DRIVER_PHONE ?? '7981212220';
  const countryCode = process.env.TWILIO_DEFAULT_COUNTRY_CODE ?? '+91';
  const formattedPhone = rawPhone.startsWith('+') ? rawPhone : `${countryCode}${rawPhone}`;

  const existingDriver = await driverRepo.findOne({ where: { driverId } });
  if (existingDriver) {
    let dirty = false;
    if (existingDriver.contactNumber !== rawPhone) {
      existingDriver.contactNumber = rawPhone;
      dirty = true;
    }
    if (!existingDriver.isActive) {
      existingDriver.isActive = true;
      dirty = true;
    }
    if (dirty) await driverRepo.save(existingDriver);
    log(`ℹ️  Driver already exists: ${driverId} (${rawPhone})`);
  } else {
    await driverRepo.save(
      driverRepo.create({
        driverId,
        firstName: 'Admin',
        secondName: null,
        surname: 'Test',
        contactNumber: rawPhone,
        isActive: true,
        isDriver: true,
        shiftA: true,
      }),
    );
    log(`✅ Seeded driver: ${driverId} (${rawPhone})`);
  }

  // Purge any leftover OTP row for this phone — only fresh, server-generated
  // OTPs are valid going forward.
  const stale = await otpRepo.findOne({ where: { phone: formattedPhone } });
  if (stale) {
    await otpRepo.remove(stale);
    log(`🧹 Cleared stale OTP fixture for ${formattedPhone}`);
  }
}

async function run(): Promise<void> {
  await AppDataSource.initialize();
  try {
    await seedAdminUser();
    await seedDriver();
    log('');
    log('Login credentials:');
    log('  • Admin web   admin@sendo.local / ChangeMe!123');
    log('  • Supervisor  x-emp-password header = tracker123 (or $EMPLOYEE_TRACKER_PASSWORD)');
    log('  • Driver      phone 7981212220 → tap "Send OTP" → enter OTP from SMS');
    log('                Twilio not configured? backend logs print: "OTP for +91… is XXXX"');
  } finally {
    await AppDataSource.destroy();
  }
}

run().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
